# -*- coding: utf-8 -*-
"""Peacock Solar DA algo_KNN

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-jbAYrp0L7mdd6iU-7OssQQ_T0GZnYj_
"""

import pandas as pd
import numpy as np
from numpy import genfromtxt

df = pd.read_excel (r'DA.xlsx') #place "r" before the path string to address special character, such as '\'. Don't forget to put the file name at the end of the path + '.xlsx'
print (df)

df.to_csv('file1.csv') 

df= pd.read_csv("file1.csv") 

y = df[["Income"]]
x = df[["AGE","Married", "Gender" , "Organization",	"Home",	"Floors" ,	"People",	"Rooms",	"Add Floor",	"Roof Percent",	"House Size",	"Loan","2 Wheeler",	"4 Wheeler",	"Payment Mode",	"EMI",	"Google",	"Facebook",	"Whatsapp",	"Youtube",	"Other",	"Aware",	"Y1",	"Y2",	"Y3",	"Y4",	"Y5",	"Y6",	"Y7",	"Y8",	"N1",	"N2",	"N3",	"N4",	"N5",	"N6",	"N7",	"N8",	"N9",	"Saving",	"Investment",	"P1",	"P2",	"Friend",	"Company",	"You own"]]

df

from sklearn.model_selection import train_test_split
x_train, x_test, y_train,y_test = train_test_split(x,y,test_size=0.20)

from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
scaler.fit(x_train)

x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)

from sklearn.neighbors import KNeighborsClassifier

classifier = KNeighborsClassifier(n_neighbors = 4)

classifier.fit(x_train, y_train)

y_pred = classifier.predict(x_test)

from sklearn.metrics import classification_report, confusion_matrix

print(classification_report(y_test, y_pred))

print(confusion_matrix(y_test, y_pred))