# -*- coding: utf-8 -*-
"""Peacock Solar Behavior Analysis

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FxARAmUEhWIR39saBqD9ncSUDorqE4vK
"""

import pandas as pd
import numpy as np
from numpy import genfromtxt

df = pd.read_excel (r'DA.xlsx') #place "r" before the path string to address special character, such as '\'. Don't forget to put the file name at the end of the path + '.xlsx'
print (df)

df.to_csv('file1.csv') 

df= pd.read_csv("file1.csv")

y = df[["Income"]]

x = df[["Y1",	"Y2",	"Y3",	"Y4",	"Y5",	"Y6",	"Y7",	"Y8",	"N1",	"N2",	"N3",	"N4",	"N5",	"N6",	"N7",	"N8",	"N9"]]

x = df["Y1"]+df["Y2"]+df["Y3"]+df["Y4"]+df["Y5"]+df["Y6"]+df["Y7"]+df["Y8"]-(df["N1"]+df["N2"]+df["N3"]+df["N4"]+df["N5"]+df["N6"]+df["N7"]+df["N8"]+df["N9"])

x=np.asarray(x)
x

x1= np.count_nonzero(x>=-45)
x2 = np.count_nonzero(x>=-28)

XL=x1-x2

x3 = np.count_nonzero(x>=-11)

Xl=x2-x3

x4 = np.count_nonzero(x>=6)

x0 = x3-x4

x5 = np.count_nonzero(x>=23)

Xm = x4-x5

print(XL)
print(Xl)
print(x0)
print(Xm)
print(x5)